server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://rm-bp1j9zo7j4d3ybzhbeo.mysql.rds.aliyuncs.com:3306/aiproject?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ENC(fFZ80nsvSTdJa/D4+gJ5NuJqB+dWS0PQ8ulkGug/JJ02ENrfJNeHgdlJ1PnCHCRo)
    password: ENC(P2tFtMzu92zu+/kVLJugk/xyGLW8FF9Q24yvdvrVR9BtpL50ilEA29X+a/NT5Ju0)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:logback-spring.xml

jasypt:
  encryptor:
    password: ${jasypt.encryptor.password}


